viso_odom_calculator:
  rate: 5
  sigma_x: 0.1
  sigma_y: 0.1
  sigma_z: 0.5
  sigma_roll: 0.5
  sigma_pitch: 0.5
  sigma_yaw: 0.1
  twist_proportional_sigma: true
  force_feedback_sigma: 1.0
  distribution_feedback_minimum_sigma: 0.1
  max_feedback_time: 0

biped_particle_odometry:
  particle_num: 80
  rate: 50
  